services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        command: gunicorn django_portfolio.wsgi --bind 0.0.0.0:8000 --log-level debug
        volumes:
            - static_volume:/home/app/web/staticfiles
        expose:
            - 8000
        env_file:
            - ./.env.prod
    db:
        volumes:
            - postgres_data_prod:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/staticfiles
        ports:
            - 1337:80
        depends_on:
            - web
volumes:
    postgres_data_prod:
    static_volume: