services:
    web:
        build: ./app
        command: gunicorn django_portfolio.wsgi --bind 0.0.0.0:8000 --log-level debug
        expose:
            - 8000
        env_file:
            - ./.env.prod
    db:
        volumes:
            - postgres_data_prod:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web
volumes:
    postgres_data_prod: