services:
    web:
        image: rafac2/pila2-tarea-20210510
        depends_on:
            - db
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data: