# Generated by Django 3.2.2 on 2021-05-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experiencia_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='portfolio.curriculum'),
        ),
    ]
